### ISSUE TITLE
Data pipe run returns -1 error message.

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pipes#63]
- First run completed without problems
- Second run generates error: typeerror: undefined is not a function
- No log file
Run document:
{
  "_id": "ca034a651e8f7e7484844dc268b321fc",
  "_rev": "1-eb1e7b4083e9305999c4144ff5356079",
  "type": "run",
  "startTime": "2015-10-06T22:01:14.577Z",
  "pipeId": "8f5603a25fbbb3be153f8131b4fe21b9",
  "status": "NOT_STARTED",
  "error": null,
  "tableStats": {},
  "message": "",
  "step0": {
    "label": "Connecting to SalesForce",
    "status": "NOT_STARTED",
    "error": ""
  },
  "step1": {
    "label": "Moving data from SalesForce to Cloudant",
    "status": "NOT_STARTED",
    "error": ""
  },
  "step2": {
    "label": "Creating and running DataWorks activities",
    "status": "NOT_STARTED",
    "error": ""
  },
  "step3": {
    "label": "Monitoring DataWorks activities for completion",
    "status": "NOT_STARTED",
    "error": ""
  }
}

**Comment by ptitzler** [comment]
The issue is triggered if a user attempts to start a pipe run while another run is in progress. There's a bug in server/pipeRunStats that causes the exception. Under normal circumstances the UI should prevent this scenario but in the virtual RF QA environment that's not the case.

**Comment by ptitzler** [comment]
The problem is not connector specific.

**Comment by ptitzler** [comment]
The following traceback information can sometimes be found in the log file: {"name":"pipesRun","hostname":"191u006fpsb","pid":29,"level":50,"err":{"message":"undefined is not a function","name":"TypeError","stack":"TypeError: undefined is not a function\n    at pipeRunStats.start (/home/vcap/app/server/pipeRunStats.js:100:22)\n    at pipeRunner.<anonymous> (/home/vcap/app/server/pipeRunner.js:68:17)\n    at /home/vcap/app/server/pipeRunStats.js:51:23\n    at storage.<anonymous> (/home/vcap/app/server/pipeStorage.js:392:10)\n    at storage.<anonymous> (/home/vcap/app/server/storage.js:267:14)\n    at Request._callback (/home/vcap/app/node_modules/cloudant/node_modules/nano/lib/nano.js:210:16)\n    at Request.self.callback (/home/vcap/app/node_modules/request/request.js:197:22)\n    at Request.emit (events.js:110:17)\n    at Request.<anonymous> (/home/vcap/app/node_modules/request/request.js:1050:14)\n    at Request.emit (events.js:129:20)\n    at IncomingMessage.<anonymous> (/home/vcap/app/node_modules/request/request.js:996:12)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n    at process._tickCallback (node.js:355:11)"},"msg":"undefined is not a function","time":"2015-10-13T00:13:09.251Z","src":{"file":"/home/vcap/app/server/pipeRunStats.js","line":131,"func":"done"},"v":0}

**Comment by ptitzler** [comment]
Fixed.
